/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package take.away.restaurant.managements;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;

public class AddressForm extends javax.swing.JFrame {

    public static List address, card, order, restaurant, user, menulist;
    public static Connection connection;

    /**
     * Creates new form AddressForm
     */
    public AddressForm() {
        initComponents();
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/tarm", "root", "");
            JOptionPane.showMessageDialog(null, "Connection True!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed!" + e.getMessage());
        }
        refresh_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Address_ADD = new javax.swing.JButton();
        Add_Edit = new javax.swing.JButton();
        Ad_Delete = new javax.swing.JButton();
        jadd_id = new javax.swing.JTextField();
        jad_u_id = new javax.swing.JTextField();
        jadd_u_name = new javax.swing.JTextField();
        jadd_u_surname = new javax.swing.JTextField();
        jad_addline1 = new javax.swing.JTextField();
        jadd_addline2 = new javax.swing.JTextField();
        jaddcity = new javax.swing.JTextField();
        jad_state = new javax.swing.JTextField();
        jad_zipcode = new javax.swing.JTextField();
        jad_country = new javax.swing.JTextField();
        jad_phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Address ID:");

        jLabel2.setText("User ID:");

        jLabel9.setText("User Name:");

        jLabel10.setText("AddressLine1:");

        jLabel11.setText("AddressLine2:");

        jLabel12.setText("User Surname:");

        jLabel13.setText("Country:");

        jLabel14.setText("City:");

        jLabel15.setText("Zipcode:");

        jLabel16.setText("State/Province/Region:");

        jLabel17.setText("Phone Number:");

        Address_ADD.setText("Add");
        Address_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_ADDActionPerformed(evt);
            }
        });

        Add_Edit.setText("Edit");
        Add_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_EditActionPerformed(evt);
            }
        });

        Ad_Delete.setText("Delete");
        Ad_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ad_DeleteActionPerformed(evt);
            }
        });

        jadd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd_idActionPerformed(evt);
            }
        });

        jaddcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddcityActionPerformed(evt);
            }
        });

        jad_zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jad_zipcodeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address ID", "User ID", "User Name", "User Surname", "Address", "Line", "City", "State", "Zipcode", "Country", "Phone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Address_ADD)
                        .addGap(18, 18, 18)
                        .addComponent(Add_Edit)
                        .addGap(18, 18, 18)
                        .addComponent(Ad_Delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jad_u_id)
                            .addComponent(jadd_u_name)
                            .addComponent(jadd_id)
                            .addComponent(jadd_u_surname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jad_addline1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jadd_addline2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jad_country, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jad_zipcode)
                            .addComponent(jad_state)
                            .addComponent(jaddcity)
                            .addComponent(jad_phone))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jadd_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jad_u_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jadd_u_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jadd_u_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jad_addline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jadd_addline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jaddcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jad_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jad_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jad_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jad_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address_ADD)
                    .addComponent(Add_Edit)
                    .addComponent(Ad_Delete))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jadd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadd_idActionPerformed

    private void jaddcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaddcityActionPerformed

    private void jad_zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jad_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jad_zipcodeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            String a = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String b = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
            String c = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String d = tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
            String e = tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
            String f = tblModel.getValueAt(jTable1.getSelectedRow(), 5).toString();
            String g = tblModel.getValueAt(jTable1.getSelectedRow(), 6).toString();
            String h = tblModel.getValueAt(jTable1.getSelectedRow(), 7).toString();
            String ı = tblModel.getValueAt(jTable1.getSelectedRow(), 8).toString();
            String j = tblModel.getValueAt(jTable1.getSelectedRow(), 9).toString();
            String k = tblModel.getValueAt(jTable1.getSelectedRow(), 10).toString();

            jadd_id.setText(a);
            jad_u_id.setText(b);
            jadd_u_name.setText(c);
            jadd_u_surname.setText(d);
            jad_addline1.setText(e);
            jadd_addline2.setText(f);
            jaddcity.setText(g);
            jad_state.setText(h);
            jad_zipcode.setText(ı);
            jad_country.setText(j);
            jad_phone.setText(k);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Zort");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void Address_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_ADDActionPerformed
        if (!jadd_id.getText().trim().isEmpty()
                && !jad_u_id.getText().trim().isEmpty()
                && !jadd_u_name.getText().trim().isEmpty()
                && !jadd_u_surname.getText().trim().isEmpty()
                && !jad_addline1.getText().trim().isEmpty()
                && !jadd_addline2.getText().trim().isEmpty()
                && !jaddcity.getText().trim().isEmpty()
                && !jad_state.getText().trim().isEmpty()
                && !jad_zipcode.getText().trim().isEmpty()
                && !jad_country.getText().trim().isEmpty()
                && !jad_phone.getText().trim().isEmpty()) {
            int ad_id = Integer.parseInt(jadd_id.getText().trim());
            int u_id = Integer.parseInt(jad_u_id.getText().trim());
            String u_name = jadd_u_name.getText().trim();
            String u_surname = jadd_u_surname.getText().trim();
            String ad_addressline1 = jad_addline1.getText().trim();
            String ad_addressline2 = jadd_addline2.getText().trim();
            String ad_city = jaddcity.getText().trim();
            String ad_state_province_region = jad_state.getText().trim();
            int ad_zipcode = Integer.parseInt(jad_zipcode.getText().trim());
            String ad_country = jad_country.getText().trim();
            String u_phone_no = jad_phone.getText().trim();

            TakeAwayRestaurantManagements.add_address(ad_id, u_id, u_name, u_surname, ad_addressline1, ad_addressline2, ad_city, ad_state_province_region, ad_zipcode, ad_country, u_phone_no);
            JOptionPane.showMessageDialog(null, "Ok!");
            refresh_JTable();

        }
    }//GEN-LAST:event_Address_ADDActionPerformed

    private void Add_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EditActionPerformed
        if (!jadd_id.getText().trim().isEmpty()
                && !jad_u_id.getText().trim().isEmpty()
                && !jadd_u_name.getText().trim().isEmpty()
                && !jadd_u_surname.getText().trim().isEmpty()
                && !jad_addline1.getText().trim().isEmpty()
                && !jadd_addline2.getText().trim().isEmpty()
                && !jaddcity.getText().trim().isEmpty()
                && !jad_state.getText().trim().isEmpty()
                && !jad_zipcode.getText().trim().isEmpty()
                && !jad_country.getText().trim().isEmpty()
                && !jad_phone.getText().trim().isEmpty()) {
            int ad_id = Integer.parseInt(jadd_id.getText().trim());
            int u_id = Integer.parseInt(jad_u_id.getText().trim());
            String u_name = jadd_u_name.getText().trim();
            String u_surname = jadd_u_surname.getText().trim();
            String ad_addressline1 = jad_addline1.getText().trim();
            String ad_addressline2 = jadd_addline2.getText().trim();
            String ad_city = jaddcity.getText().trim();
            String ad_state_province_region = jad_state.getText().trim();
            int ad_zipcode = Integer.parseInt(jad_zipcode.getText().trim());
            String ad_country = jad_country.getText().trim();
            String u_phone_no = jad_phone.getText().trim();

            TakeAwayRestaurantManagements.edit_address(ad_id, u_id, u_name, u_surname, ad_addressline1, ad_addressline2, ad_city, ad_state_province_region, ad_zipcode, ad_country, u_phone_no);
            JOptionPane.showMessageDialog(null, "Ok!");
            refresh_JTable();

        }
    }//GEN-LAST:event_Add_EditActionPerformed

    private void Ad_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ad_DeleteActionPerformed
       int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row, 0).toString();
        String sql = "DELETE FROM address where ad_id = " + cell;
        try {
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
            refresh_JTable();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_Ad_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressForm().setVisible(true);
            }
        });
    }

    public void refresh_JTable() {
        
        List address = TakeAwayRestaurantManagements.address;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[11];
        Iterator itr = address.iterator();
        Address add;
        model.setNumRows(0);

        while (itr.hasNext()) {
            add = (Address) itr.next();
            rowData[0] = add.getAd_id();
            rowData[1] = add.getU_id();
            rowData[2] = add.getU_name();
            rowData[3] = add.getU_surname();
            rowData[4] = add.getAd_addressline1();
            rowData[5] = add.getAd_addressline2();
            rowData[6] = add.getAd_city();
            rowData[7] = add.getAd_state_province_region();
            rowData[8] = add.getAd_zipcode();
            rowData[9] = add.getAd_country();
            rowData[10] = add.getU_phone_no();

            model.addRow(rowData);
        }
        try {
            ResultSet res;
            String sql = "SELECT * FROM address";
            Statement stmt = connection.createStatement();
            res = stmt.executeQuery(sql);
            while (res.next()) {
                String ad_id = res.getString("ad_id");
                String u_id = res.getString("u_id");
                String u_name = res.getString("u_name");
                String u_surname = res.getString("u_surname");
                String ad_addressline1 = res.getString("ad_addressline1");
                String ad_addressline2 = res.getString("ad_addressline2");
                String ad_city = res.getString("ad_city");
                String ad_state_province_region = res.getString("ad_state_province_region");
                String ad_zipcode = res.getString("ad_zipcode");
                String ad_country = res.getString("ad_country");
                String u_phone_no = res.getString("u_phone_no");

                String tbData[] = {ad_id, u_id, u_name, u_surname, ad_addressline1, ad_addressline2, ad_city, ad_state_province_region, ad_zipcode, ad_country, u_phone_no};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Buzlubamde" + e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ad_Delete;
    private javax.swing.JButton Add_Edit;
    private javax.swing.JButton Address_ADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jad_addline1;
    private javax.swing.JTextField jad_country;
    private javax.swing.JTextField jad_phone;
    private javax.swing.JTextField jad_state;
    private javax.swing.JTextField jad_u_id;
    private javax.swing.JTextField jad_zipcode;
    private javax.swing.JTextField jadd_addline2;
    private javax.swing.JTextField jadd_id;
    private javax.swing.JTextField jadd_u_name;
    private javax.swing.JTextField jadd_u_surname;
    private javax.swing.JTextField jaddcity;
    // End of variables declaration//GEN-END:variables
}
