/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package take.away.restaurant.managements;

import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;

public class MenuListForm extends javax.swing.JFrame {

    public static List address, card, order, restaurant, user, menulist;
    public static Connection connection;

    public MenuListForm() {
        initComponents();
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/tarm", "root", "");
            JOptionPane.showMessageDialog(null, "Connection True!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed!" + e.getMessage());
        }
        refresh_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmenu_id = new javax.swing.JTextField();
        jres_id = new javax.swing.JTextField();
        jfood_name = new javax.swing.JTextField();
        jfood_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jres_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenutable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Menu ID");

        jLabel2.setText("Restaurant ID");

        jLabel4.setText("Food Name");

        jLabel5.setText("Food Price");

        jmenu_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_idActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Restaurant Name:");

        jres_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jres_nameActionPerformed(evt);
            }
        });

        jMenutable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu ID", "Restaurant ID", "Food Name", "Food Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jMenutable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenutableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jMenutable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jmenu_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jfood_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jfood_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jres_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jres_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton4)
                            .addComponent(jres_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jmenu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jres_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jfood_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jfood_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenu_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!jmenu_id.getText().trim().isEmpty()
                && !jres_id.getText().trim().isEmpty()
                && !jfood_name.getText().trim().isEmpty()
                && !jfood_price.getText().trim().isEmpty()) {
            int menu_id = Integer.parseInt(jmenu_id.getText().trim());
            int res_id = Integer.parseInt(jres_id.getText().trim());
            String food_name = jfood_name.getText().trim();
            float food_price = Float.parseFloat(jfood_price.getText().trim());

            TakeAwayRestaurantManagements.add_menulist(menu_id, res_id, food_name, food_price);
            JOptionPane.showMessageDialog(null, "Ok!");
            refresh_JTable();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenutableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenutableMouseClicked

        try {
            DefaultTableModel tblModel = (DefaultTableModel) jMenutable.getModel();
            String a = tblModel.getValueAt(jMenutable.getSelectedRow(), 0).toString();
            String b = tblModel.getValueAt(jMenutable.getSelectedRow(), 1).toString();
            String c = tblModel.getValueAt(jMenutable.getSelectedRow(), 2).toString();
            String d = tblModel.getValueAt(jMenutable.getSelectedRow(), 3).toString();

            jmenu_id.setText(a);
            jres_id.setText(b);
            jfood_name.setText(c);
            jfood_price.setText(d);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Zort");
        }
    }//GEN-LAST:event_jMenutableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        List menulist = TakeAwayRestaurantManagements.menulist;
        DefaultTableModel model = (DefaultTableModel) jMenutable.getModel();
        Object rowData[] = new Object[4];
        Iterator itr = menulist.iterator();
        Menulist ml;
        model.setNumRows(0);

        while (itr.hasNext()) {
            ml = (Menulist) itr.next();
            rowData[0] = ml.getMenu_id();
            rowData[1] = ml.getRes_id();
            rowData[2] = ml.getFood_name();
            rowData[3] = ml.getFood_price();

            model.addRow(rowData);
        }
        try {

            ResultSet res;
            String cell = jres_id.getText();
            String sql = "SELECT * FROM menulist WHERE res_id=" + cell;
            Statement stmt = connection.createStatement();
            res = stmt.executeQuery(sql);
            while (res.next()) {
                String menu_id = res.getString("menu_id");
                String res_id = res.getString("res_id");
                String food_name = res.getString("food_name");
                String food_price = res.getString("food_price");

                String tbData[] = {menu_id, res_id, food_name, food_price};
                DefaultTableModel tblModel = (DefaultTableModel) jMenutable.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Buzlubamde" + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jres_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jres_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jres_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jMenutable.getSelectedRow();
        String cell = jMenutable.getModel().getValueAt(row, 0).toString();
        String sql = "DELETE FROM menulist where menu_id = " + cell;
        try {
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
            refresh_JTable();

        } catch (Exception e) {
        }    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuListForm().setVisible(true);
            }
        });
    }

    public void refresh_JTable() {

        List menulist1 = TakeAwayRestaurantManagements.menulist;
        DefaultTableModel model = (DefaultTableModel) jMenutable.getModel();
        Object rowData[] = new Object[4];
        Iterator itr = menulist1.iterator();
        Menulist ml;
        model.setNumRows(0);

        while (itr.hasNext()) {
            ml = (Menulist) itr.next();
            rowData[0] = ml.getMenu_id();
            rowData[1] = ml.getRes_id();
            rowData[2] = ml.getFood_name();
            rowData[3] = ml.getFood_price();

            model.addRow(rowData);
        }
        try {
            ResultSet res;
            String sql = "SELECT * FROM menulist";
            Statement stmt = connection.createStatement();
            res = stmt.executeQuery(sql);
            while (res.next()) {
                String menu_id = res.getString("menu_id");
                String res_id = res.getString("res_id");
                String food_name = res.getString("food_name");
                String food_price = res.getString("food_price");

                String tbData[] = {menu_id, res_id, food_name, food_price};
                DefaultTableModel tblModel = (DefaultTableModel) jMenutable.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Buzlubamde" + e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jMenutable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jfood_name;
    private javax.swing.JTextField jfood_price;
    private javax.swing.JTextField jmenu_id;
    private javax.swing.JTextField jres_id;
    private javax.swing.JTextField jres_name;
    // End of variables declaration//GEN-END:variables
}
