/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package take.away.restaurant.managements;

import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;

public class UserForm extends javax.swing.JFrame {

    public static List address, card, order, restaurant, user, menulist;
    public static Connection connection;

    public UserForm() {
        initComponents();
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/tarm", "root", "");
            JOptionPane.showMessageDialog(null, "Connection True!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed!" + e.getMessage());
        }
        refresh_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        juser_id = new javax.swing.JTextField();
        juser_name = new javax.swing.JTextField();
        juser_sname = new javax.swing.JTextField();
        juser_phoneno = new javax.swing.JTextField();
        juser_bdate = new javax.swing.JTextField();
        juser_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("User ID");

        jLabel2.setText("Name");

        jLabel3.setText("Surname");

        jLabel5.setText("Birthdate");

        jLabel6.setText("Email");

        juser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juser_idActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone No");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Surname", "Phone No", "BirthDate", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(juser_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(juser_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(juser_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(juser_email, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(juser_phoneno)
                            .addComponent(juser_bdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Add)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(juser_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(juser_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(juser_sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(juser_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(juser_bdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(juser_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juser_idActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            String a = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String b = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
            String c = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String d = tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
            String e = tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
            String f = tblModel.getValueAt(jTable1.getSelectedRow(), 5).toString();

            juser_id.setText(a);
            juser_name.setText(b);
            juser_sname.setText(c);
            juser_phoneno.setText(d);
            juser_bdate.setText(e);
            juser_email.setText(f);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Zort");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if (!juser_id.getText().trim().isEmpty()
                && !juser_name.getText().trim().isEmpty()
                && !juser_sname.getText().trim().isEmpty()
                && !juser_phoneno.getText().trim().isEmpty()
                && !juser_bdate.getText().trim().isEmpty()
                && !juser_email.getText().trim().isEmpty()) {
            int u_id = Integer.parseInt(juser_id.getText().trim());
            String u_name = juser_name.getText().trim();
            String u_surname = juser_sname.getText().trim();
            String u_phone_no = juser_phoneno.getText().trim();
            String u_birthdate = juser_bdate.getText().trim();
            String u_email = juser_email.getText().trim();

            TakeAwayRestaurantManagements.add_user(u_id, u_name, u_surname, u_phone_no, u_birthdate, u_email);
            JOptionPane.showMessageDialog(null, "Ok!");
            refresh_JTable();
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (!juser_id.getText().trim().isEmpty()
                && !juser_name.getText().trim().isEmpty()
                && !juser_sname.getText().trim().isEmpty()
                && !juser_phoneno.getText().trim().isEmpty()
                && !juser_bdate.getText().trim().isEmpty()
                && !juser_email.getText().trim().isEmpty()) {
            int u_id = Integer.parseInt(juser_id.getText().trim());
            String u_name = juser_name.getText().trim();
            String u_surname = juser_sname.getText().trim();
            String u_phone_no = juser_phoneno.getText().trim();
            String u_birthdate = juser_bdate.getText().trim();
            String u_email = juser_email.getText().trim();

            TakeAwayRestaurantManagements.edit_user(u_id, u_name, u_surname, u_phone_no, u_birthdate, u_email);
            JOptionPane.showMessageDialog(null, "Ok!");
            refresh_JTable();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row, 0).toString();
        String sql = "DELETE FROM user where u_id = " + cell;
        try {
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
            refresh_JTable();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    public void refresh_JTable() {
        List user = TakeAwayRestaurantManagements.user;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[6];
        Iterator itr = user.iterator();
        User us;
        model.setNumRows(0);

        while (itr.hasNext()) {
            us = (User) itr.next();
            rowData[0] = us.getU_id();
            rowData[1] = us.getU_name();
            rowData[2] = us.getU_surname();
            rowData[3] = us.getU_phone_no();
            rowData[4] = us.getU_birthdate();
            rowData[5] = us.getU_email();

            model.addRow(rowData);
        }
        try {
            ResultSet res;
            String sql = "SELECT * FROM user";
            Statement stmt = connection.createStatement();
            res = stmt.executeQuery(sql);
            while (res.next()) {
                String u_id = res.getString("u_id");
                String u_name = res.getString("u_name");
                String u_surname = res.getString("u_surname");
                String u_phone_no = res.getString("u_phone_no");
                String u_birthdate = res.getString("u_birthdate");
                String u_email = res.getString("u_email");

                String tbData[] = {u_id, u_name, u_surname, u_phone_no, u_birthdate, u_email};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Buzlubamde" + e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField juser_bdate;
    private javax.swing.JTextField juser_email;
    private javax.swing.JTextField juser_id;
    private javax.swing.JTextField juser_name;
    private javax.swing.JTextField juser_phoneno;
    private javax.swing.JTextField juser_sname;
    // End of variables declaration//GEN-END:variables
}
